# Generated by Django 4.2.27 on 2026-01-28 18:02

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stripe_charge_id', models.CharField(max_length=255, unique=True, verbose_name='Stripe Charge/PaymentIntent ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount')),
                ('currency', models.CharField(choices=[('USD', 'US Dollar'), ('KES', 'Kenyan Shilling'), ('NGN', 'Nigerian Naira'), ('GHS', 'Ghanaian Cedi')], default='USD', max_length=3, verbose_name='Currency')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20, verbose_name='Status')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Paid At')),
            ],
            options={
                'verbose_name': 'Payment Transaction',
                'verbose_name_plural': 'Payment Transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Plan Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('stripe_price_id', models.CharField(help_text='The ID of the Price object in Stripe (e.g., price_xxxxxxxxxxxxxx)', max_length=255, unique=True, verbose_name='Stripe Price ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price')),
                ('currency', models.CharField(choices=[('USD', 'US Dollar'), ('KES', 'Kenyan Shilling'), ('NGN', 'Nigerian Naira'), ('GHS', 'Ghanaian Cedi')], default='USD', max_length=3, verbose_name='Currency')),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Monthly'), ('annually', 'Annually'), ('quarterly', 'Quarterly')], default='monthly', max_length=20, verbose_name='Billing Cycle')),
                ('features', models.JSONField(blank=True, default=dict, help_text='Key-value pairs of features for this plan.')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive plans are not offered to new subscribers.', verbose_name='Is Active')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Order for displaying plans, lower numbers first.')),
            ],
            options={
                'verbose_name': 'Subscription Plan',
                'verbose_name_plural': 'Subscription Plans',
                'ordering': ['display_order', 'price'],
            },
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stripe_subscription_id', models.CharField(max_length=255, unique=True, verbose_name='Stripe Subscription ID')),
                ('stripe_customer_id', models.CharField(max_length=255, verbose_name='Stripe Customer ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('trialing', 'Trialing'), ('past_due', 'Past Due'), ('cancelled', 'Cancelled'), ('incomplete', 'Incomplete'), ('pending_cancellation', 'Pending Cancellation')], default='incomplete', max_length=30, verbose_name='Status')),
                ('current_period_end', models.DateTimeField(blank=True, null=True, verbose_name='Current Period End')),
                ('cancel_at_period_end', models.BooleanField(default=False, verbose_name='Cancel at Period End')),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='payments.subscriptionplan', verbose_name='Plan')),
            ],
            options={
                'verbose_name': 'User Subscription',
                'verbose_name_plural': 'User Subscriptions',
            },
        ),
    ]
