# Generated by Django 4.2.27 on 2026-01-31 03:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymenttransaction',
            name='stripe_charge_id',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='stripe_price_id',
        ),
        migrations.RemoveField(
            model_name='usersubscription',
            name='current_period_end',
        ),
        migrations.RemoveField(
            model_name='usersubscription',
            name='stripe_customer_id',
        ),
        migrations.RemoveField(
            model_name='usersubscription',
            name='stripe_subscription_id',
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, verbose_name='Metadata'),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='payment_method',
            field=models.CharField(choices=[('paystack', 'Paystack'), ('bank_transfer', 'Bank Transfer'), ('card', 'Card')], default='paystack', max_length=20, verbose_name='Payment Method'),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='paystack_reference',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Paystack Reference'),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='transaction_id',
            field=models.CharField(default=django.utils.timezone.now, max_length=255, unique=True, verbose_name='Transaction Reference'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='paystack_plan_code',
            field=models.CharField(blank=True, help_text='The plan code from Paystack', max_length=255, null=True, verbose_name='Paystack Plan Code'),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='End Date'),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='paystack_customer_code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Paystack Customer Code'),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='paystack_subscription_code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Paystack Subscription Code'),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar'), ('KES', 'Kenyan Shilling'), ('NGN', 'Nigerian Naira'), ('GHS', 'Ghanaian Cedi')], default='NGN', max_length=3, verbose_name='Currency'),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar'), ('KES', 'Kenyan Shilling'), ('NGN', 'Nigerian Naira'), ('GHS', 'Ghanaian Cedi')], default='NGN', max_length=3, verbose_name='Currency'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='display_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='features',
            field=models.JSONField(blank=True, default=list, help_text='List of features for this plan.'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active'),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('trialing', 'Trialing'), ('past_due', 'Past Due'), ('cancelled', 'Cancelled'), ('incomplete', 'Incomplete'), ('pending', 'Pending')], default='pending', max_length=30, verbose_name='Status'),
        ),
    ]
