# Generated by Django 4.2.27 on 2026-01-28 18:02

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='Project Title')),
                ('slug', models.SlugField(max_length=220, unique=True, verbose_name='Slug')),
                ('description', models.TextField(verbose_name='Project Description')),
                ('difficulty_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], default='intermediate', max_length=20, verbose_name='Difficulty Level')),
                ('estimated_duration_hours', models.PositiveIntegerField(blank=True, help_text='Estimated time a user might spend on this project.', null=True, verbose_name='Estimated Duration (Hours)')),
                ('learning_outcomes', models.JSONField(blank=True, default=list, help_text='List of skills or concepts the user will learn or apply.', verbose_name='Learning Outcomes')),
                ('prerequisites', models.JSONField(blank=True, default=list, help_text='List of skills or courses recommended before starting this project.', verbose_name='Prerequisites')),
                ('guidelines', models.JSONField(blank=True, default=dict, help_text="Structured details: e.g., {'user_stories': [], 'technical_requirements': [], 'submission_format': ''}", verbose_name='Project Guidelines & Requirements')),
                ('resources', models.JSONField(blank=True, default=list, help_text="List of URLs or references, e.g., [{'title': 'API Docs', 'url': '...'}].", verbose_name='Helpful Resources')),
                ('is_published', models.BooleanField(default=False, verbose_name='Is Published')),
                ('ai_generated', models.BooleanField(default=False, verbose_name='AI Generated')),
                ('ai_generation_prompt', models.TextField(blank=True, null=True, verbose_name='AI Generation Prompt Used')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Project Definition',
                'verbose_name_plural': 'Project Definitions',
                'ordering': ['-created_at', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ProjectAssessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assessed_by_ai', models.BooleanField(default=True, verbose_name='Assessed by AI Agent')),
                ('assessor_ai_agent_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='AI Agent Name/Version')),
                ('score', models.FloatField(blank=True, help_text='Overall score given by the assessment.', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)], verbose_name='Assessment Score (0-100)')),
                ('passed', models.BooleanField(default=False, verbose_name='Passed Assessment')),
                ('feedback_summary', models.TextField(blank=True, null=True, verbose_name='Feedback Summary')),
                ('detailed_feedback', models.JSONField(blank=True, default=dict, help_text="Structured feedback, e.g., {'criteria_met': [], 'improvement_points': [], 'ai_tutor_trigger_reason': '...'}", verbose_name='Detailed Feedback')),
                ('assessed_at', models.DateTimeField(auto_now_add=True, verbose_name='Assessed At')),
            ],
            options={
                'verbose_name': 'Project Assessment',
                'verbose_name_plural': 'Project Assessments',
                'ordering': ['-assessed_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Submitted At')),
                ('submission_notes', models.TextField(blank=True, null=True, verbose_name='Submission Notes by User')),
                ('submission_artifacts', models.JSONField(blank=True, default=dict, help_text="e.g., {'repository_url': '...', 'live_demo_url': '...', 'file_links': ['...']}. UserProject URLs can be primary.", verbose_name='Submission Artifacts')),
                ('submission_version', models.PositiveIntegerField(default=1, verbose_name='Submission Version')),
            ],
            options={
                'verbose_name': 'Project Submission',
                'verbose_name_plural': 'Project Submissions',
                'ordering': ['user_project', '-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Tag Name')),
                ('slug', models.SlugField(max_length=60, unique=True, verbose_name='Slug')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Project Tag',
                'verbose_name_plural': 'Project Tags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserProject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('submitted', 'Submitted for Assessment'), ('assessed', 'Assessed'), ('completed', 'Completed Successfully'), ('failed', 'Failed Assessment'), ('archived', 'Archived')], default='not_started', max_length=30, verbose_name='Status')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Started At')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed At')),
                ('repository_url', models.URLField(blank=True, null=True, verbose_name='Project Repository URL (e.g., GitHub)')),
                ('live_url', models.URLField(blank=True, null=True, verbose_name='Live Project URL (e.g., deployed app)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Assigned/Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated At')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_instances', to='projects.project', verbose_name='Project Definition')),
            ],
            options={
                'verbose_name': 'User Project Instance',
                'verbose_name_plural': 'User Project Instances',
                'ordering': ['-updated_at', '-created_at'],
            },
        ),
    ]
