# Generated by Django 4.2.27 on 2026-01-28 18:02

from django.conf import settings
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='email address')),
                ('full_name', models.CharField(blank=True, max_length=255, verbose_name='Full Name')),
                ('organization', models.CharField(blank=True, max_length=255, null=True, verbose_name='Organization/College/School')),
                ('industry', models.CharField(blank=True, choices=[('Technology', 'Technology'), ('Finance', 'Finance'), ('Healthcare', 'Healthcare'), ('Education', 'Education'), ('Retail', 'Retail'), ('Manufacturing', 'Manufacturing'), ('Consulting', 'Consulting'), ('Government', 'Government'), ('Non-Profit', 'Non-Profit'), ('Other', 'Other')], db_index=True, max_length=100, null=True, verbose_name='Industry')),
                ('other_industry_details', models.CharField(blank=True, max_length=255, null=True, verbose_name='Other Industry Details')),
                ('profession', models.CharField(blank=True, max_length=255, null=True, verbose_name='Profession')),
                ('whatsapp_number', models.CharField(blank=True, db_index=True, max_length=20, null=True, unique=True, verbose_name='WhatsApp Number')),
                ('is_whatsapp_verified', models.BooleanField(default=False, verbose_name='WhatsApp Verified')),
                ('whatsapp_verification_code', models.CharField(blank=True, max_length=6, null=True, verbose_name='WhatsApp Code')),
                ('whatsapp_code_created_at', models.DateTimeField(blank=True, null=True, verbose_name='WhatsApp Code Created At')),
                ('preferred_language', models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('fr', 'French'), ('de', 'German'), ('zh', 'Chinese'), ('ja', 'Japanese'), ('pt', 'Portuguese'), ('ru', 'Russian'), ('ar', 'Arabic'), ('hi', 'Hindi')], db_index=True, default='en', max_length=10, verbose_name='Language')),
                ('preferred_currency', models.CharField(choices=[('USD', 'US Dollar'), ('KES', 'Kenyan Shilling'), ('NGN', 'Nigerian Naira'), ('GHS', 'Ghanaian Cedi')], default='USD', max_length=3, verbose_name='Currency')),
                ('profile_picture_url', models.URLField(blank=True, max_length=1024, null=True, verbose_name='Profile Picture URL')),
                ('uplas_xp_points', models.PositiveIntegerField(default=0, verbose_name='XP Points')),
                ('is_premium_subscriber', models.BooleanField(db_index=True, default=False, verbose_name='Is Premium')),
                ('country', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Country')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='City')),
                ('stripe_customer_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'ordering': ['-date_joined'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bio', models.TextField(blank=True, null=True, verbose_name='Bio')),
                ('linkedin_url', models.URLField(blank=True, null=True, verbose_name='LinkedIn URL')),
                ('github_url', models.URLField(blank=True, null=True, verbose_name='GitHub URL')),
                ('website_url', models.URLField(blank=True, null=True, verbose_name='Website URL')),
                ('preferred_tutor_persona', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tutor Persona')),
                ('learning_goals', models.TextField(blank=True, null=True, verbose_name='Learning Goals')),
                ('career_interest', models.CharField(blank=True, max_length=255, null=True, verbose_name='Career Interest')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
    ]
